resolver: lts-22.18

allow-newer: true
notify-if-nix-on-path: false
recommend-stack-upgrade: true
stack-developer-mode: true
system-ghc: true

nix:
  enable: true
  packages: [zlib]

ghc-options:
  '$everything': -haddock

packages:
  - .
