resolver: lts-22.18

allow-newer: false
notify-if-nix-on-path: false
recommend-stack-upgrade: false
stack-developer-mode: true
system-ghc: true

nix:
  enable: true
  packages: [zlib]


ghc-options:
  '$everything': -haddock

packages:
  - .
